# -*- coding: utf-8 -*-
'''
@Time :  11:09
@Author : maodongdong
@File : service_fulfillment.py
'''

#正常场景参数
success_data = {
    "@class":"com.evisible.hnfh.entity.domain.CreditApplyParam",
    "financialStatements":[
        {
            "id":207,
            "entityUuid":"687a398b-65d8-455f-963b-3571a2788ea3",
            "createdTime":"2021-04-23 17:21:20",
            "createdBy":"hnfh_test6_gys_4716",
            "attachments":[

            ],
            "lastUpdateTime":"2021-04-23 17:21:20",
            "lastUpdateBy":"hnfh_test6_gys_4716",
            "orgId":"4641a7ca-2c2c-4ddd-aa0b-b2d678b1ee26",
            "orgName":"一天开花有限公司",
            "orgRole":"HNFH_SUPPLIER",
            "reportPeriod":"MONTHLY",
            "reportScope":"HQ",
            "reportDate":"2021-01",
            "auditUnit":"",
            "comments":"",
            "finStatementDetail":{
                "reportDate":"2021-01",
                "reportScope":"02",
                "reportPeriod":"01",
                "reportCurrency":"CNY",
                "reportUnit":"01",
                "reportNotes":"",
                "auditFlag":"N",
                "auditOffice":"",
                "auditOpinion":"",
                "reportDetailInfo":{
                    "balanceSheet":{
                        "liquidAssets":{
                            "balanceSheetRow1":"0",
                            "balanceSheetRow2":"0",
                            "balanceSheetRow3":"9",
                            "balanceSheetRow4":"0",
                            "balanceSheetRow5":"0",
                            "balanceSheetRow6":"0",
                            "balanceSheetRow7":"0",
                            "balanceSheetRow8":"9",
                            "balanceSheetRow9":"9",
                            "balanceSheetRow10":"9",
                            "balanceSheetRow11":"9",
                            "balanceSheetRow12":"9"
                        },
                        "nonCurrentAssets":{
                            "balanceSheetRow15":"9",
                            "balanceSheetRow16":"9",
                            "balanceSheetRow17":"9",
                            "balanceSheetRow18":"9",
                            "balanceSheetRow19":"9",
                            "balanceSheetRow20":"9",
                            "balanceSheetRow21":"9",
                            "balanceSheetRow22":"9",
                            "balanceSheetRow23":"9",
                            "balanceSheetRow24":"9",
                            "balanceSheetRow25":"9",
                            "balanceSheetRow26":"9",
                            "balanceSheetRow27":"9",
                            "balanceSheetRow28":"9",
                            "balanceSheetRow29":"9",
                            "balanceSheetRow30":"9",
                            "balanceSheetRow31":"9",
                            "balanceSheetRow32":"9"
                        },
                        "currentLiabilities":{
                            "balanceSheetRow36":"9",
                            "balanceSheetRow37":"9",
                            "balanceSheetRow38":"9",
                            "balanceSheetRow39":"9",
                            "balanceSheetRow40":"9",
                            "balanceSheetRow41":"9",
                            "balanceSheetRow42":"9",
                            "balanceSheetRow43":"9",
                            "balanceSheetRow44":"9",
                            "balanceSheetRow45":"9",
                            "balanceSheetRow46":"9",
                            "balanceSheetRow47":"9",
                            "balanceSheetRow48":"9"
                        },
                        "nonCurrentLiabilities":{
                            "balanceSheetRow51":"9",
                            "balanceSheetRow52":"9",
                            "balanceSheetRow53":"9",
                            "balanceSheetRow54":"9",
                            "balanceSheetRow55":"9",
                            "balanceSheetRow56":"9",
                            "balanceSheetRow57":"9"
                        },
                        "ownershipInterest":{
                            "balanceSheetRow61":"9",
                            "balanceSheetRow62":"9",
                            "balanceSheetRow63":"9",
                            "balanceSheetRow64":"9",
                            "balanceSheetRow65":"9",
                            "balanceSheetRow66":"9",
                            "balanceSheetRow67":"9"
                        }
                    },
                    "cashFlowStatement":{
                        "operatingActivitiesCashFlow":{
                            "cashFlowStatementRow1":"8",
                            "cashFlowStatementRow2":"8",
                            "cashFlowStatementRow3":"8",
                            "cashFlowStatementRow5":"8",
                            "cashFlowStatementRow6":"8",
                            "cashFlowStatementRow7":"8",
                            "cashFlowStatementRow8":"8"
                        },
                        "investmentActivitiesCashFlow":{
                            "cashFlowStatementRow12":"8",
                            "cashFlowStatementRow13":"8",
                            "cashFlowStatementRow14":"8",
                            "cashFlowStatementRow15":"8",
                            "cashFlowStatementRow16":"8",
                            "cashFlowStatementRow18":"8",
                            "cashFlowStatementRow19":"8",
                            "cashFlowStatementRow20":"8",
                            "cashFlowStatementRow21":"8"
                        },
                        "financingActivitiesCashFlow":{
                            "cashFlowStatementRow25":"8",
                            "cashFlowStatementRow26":"8",
                            "cashFlowStatementRow27":"8",
                            "cashFlowStatementRow29":"8",
                            "cashFlowStatementRow30":"8",
                            "cashFlowStatementRow31":"8"
                        },
                        "cashFlowStatementRow34":"8"
                    },
                    "incomeStatement":{
                        "operatingProfit":{
                            "incomeStatementRow0":"7",
                            "incomeStatementRow1":"7",
                            "incomeStatementRow2":"7",
                            "incomeStatementRow3":"7",
                            "incomeStatementRow4":"7",
                            "incomeStatementRow5":"7",
                            "incomeStatementRow6":"7",
                            "incomeStatementRow7":"7",
                            "incomeStatementRow8":"7",
                            "incomeStatementRow9":"7"
                        },
                        "incomeStatementRow11":"7",
                        "incomeStatementRow12":"7",
                        "incomeStatementRow13":"7",
                        "incomeStatementRow15":"7",
                        "incomeStatementRow17":"7",
                        "incomeStatementRow18":"7",
                        "incomeStatementRow19":"7"
                    }
                }
            },
            "audit":"false",
            "@class":"com.evisible.hnfh.entity.domain.FinancialStatement"
        }
    ],
    "grantedCredit":{
        "id":252,
        "attachments":[
            {
                "uid":"1619169367734",
                "fileId":"60829116c0a4710007ce6b4f",
                "fileName":"1.jpg",
                "contentType":"",
                "size":58231,
                "updateTime":"",
                "md5":"",
                "content":"",
                "hash":"",
                "dataPoolURL":"",
                "description":"",
                "type":"0105",
                "name":"1.jpg",
                "status":"success",
                "fileAddr":"/api/files/file/query/60829116c0a4710007ce6b4f"
            },
            {
                "uid":"1619169371003",
                "fileId":"60829119c0a4710007ce6b51",
                "fileName":"2.jpg",
                "contentType":"",
                "size":40290,
                "updateTime":"",
                "md5":"",
                "content":"",
                "hash":"",
                "dataPoolURL":"",
                "description":"",
                "type":"0106",
                "name":"2.jpg",
                "status":"success",
                "fileAddr":"/api/files/file/query/60829119c0a4710007ce6b51"
            },
            {
                "uid":"1619169374558",
                "fileId":"6082911dc0a4710007ce6b53",
                "fileName":"3.jpg",
                "contentType":"",
                "size":53157,
                "updateTime":"",
                "md5":"",
                "content":"",
                "hash":"",
                "dataPoolURL":"",
                "description":"",
                "type":"0101",
                "name":"3.jpg",
                "status":"success",
                "fileAddr":"/api/files/file/query/6082911dc0a4710007ce6b53"
            },
            {
                "uid":"1619169378151",
                "fileId":"60829120c0a4710007ce6b55",
                "fileName":"4.jpg",
                "contentType":"",
                "size":58317,
                "updateTime":"",
                "md5":"",
                "content":"",
                "hash":"",
                "dataPoolURL":"",
                "description":"",
                "type":"0118",
                "name":"4.jpg",
                "status":"success",
                "fileAddr":"/api/files/file/query/60829120c0a4710007ce6b55"
            },
            {
                "uid":1620280221606,
                "size":252030,
                "fileId":"60938450c0a4710007ce6d5b",
                "fileName":"发票3.jpg",
                "name":"发票3.jpg",
                "status":"success",
                "type":"0123",
                "fileAddr":"/api/files/file/query/60938450c0a4710007ce6d5b"
            },
            {
                "uid":"1619169383138",
                "fileId":"60829125c0a4710007ce6b57",
                "fileName":"5.jpg",
                "contentType":"",
                "size":55985,
                "updateTime":"",
                "md5":"",
                "content":"",
                "hash":"",
                "dataPoolURL":"",
                "description":"",
                "type":"0114",
                "name":"5.jpg",
                "status":"success",
                "fileAddr":"/api/files/file/query/60829125c0a4710007ce6b57"
            },
            {
                "uid":"1619169387254",
                "fileId":"60829129c0a4710007ce6b59",
                "fileName":"6.jpg",
                "contentType":"",
                "size":53090,
                "updateTime":"",
                "md5":"",
                "content":"",
                "hash":"",
                "dataPoolURL":"",
                "description":"",
                "type":"0115",
                "name":"6.jpg",
                "status":"success",
                "fileAddr":"/api/files/file/query/60829129c0a4710007ce6b59"
            },
            {
                "uid":"1619169390776",
                "fileId":"6082912dc0a4710007ce6b5b",
                "fileName":"7.jpg",
                "contentType":"",
                "size":63302,
                "updateTime":"",
                "md5":"",
                "content":"",
                "hash":"",
                "dataPoolURL":"",
                "description":"",
                "type":"0116",
                "name":"7.jpg",
                "status":"success",
                "fileAddr":"/api/files/file/query/6082912dc0a4710007ce6b5b"
            },
            {
                "uid":1620280226293,
                "size":549598,
                "fileId":"60938457c0a4710007ce6d5d",
                "fileName":"发票2.jpg",
                "name":"发票2.jpg",
                "status":"success",
                "type":"0117",
                "fileAddr":"/api/files/file/query/60938457c0a4710007ce6d5d"
            },
            {
                "uid":1620280237233,
                "size":158007,
                "fileId":"6093845fc0a4710007ce6d61",
                "fileName":"发票.jpg",
                "name":"发票.jpg",
                "status":"success",
                "type":"0112",
                "fileAddr":"/api/files/file/query/6093845fc0a4710007ce6d61"
            },
            {
                "uid":1620280242124,
                "size":38868,
                "fileId":"60938463c0a4710007ce6d63",
                "fileName":"滴滴电子发票.pdf",
                "name":"滴滴电子发票.pdf",
                "status":"success",
                "type":"0113",
                "fileAddr":"/api/files/file/query/60938463c0a4710007ce6d63"
            },
            {
                "uid":"1619169394551",
                "fileId":"60829131c0a4710007ce6b5d",
                "fileName":"8.jpg",
                "contentType":"",
                "size":97420,
                "updateTime":"",
                "md5":"",
                "content":"",
                "hash":"",
                "dataPoolURL":"",
                "description":"",
                "type":"0102",
                "name":"8.jpg",
                "status":"success",
                "fileAddr":"/api/files/file/query/60829131c0a4710007ce6b5d"
            },
            {
                "uid":"1619169398740",
                "fileId":"60829135c0a4710007ce6b5f",
                "fileName":"9.jpg",
                "contentType":"",
                "size":61747,
                "updateTime":"",
                "md5":"",
                "content":"",
                "hash":"",
                "dataPoolURL":"",
                "description":"",
                "type":"0103",
                "name":"9.jpg",
                "status":"success",
                "fileAddr":"/api/files/file/query/60829135c0a4710007ce6b5f"
            }
        ],
        "@class":"com.evisible.hnfh.entity.domain.GrantedCredit",
        "orgId":"4641a7ca-2c2c-4ddd-aa0b-b2d678b1ee26",
        "orgName":"一天开花有限公司",
        "orgRole":"HNFH_SUPPLIER",
        "authLoanExtInfo":{
            "serviceAddress":"北京",
            "postalCode":"121231",
            "corporationName":"张翰",
            "contactsName":"冬冬6",
            "contactTelephone":"17664222137",
            "totalAccountsReceivableAmount":"",
            "loanAmt":"",
            "loanEndDate":"",
            "accountsReceivableList":""
        },
        "pattern":"PATTERN_B",
        "applyCreditRequest":{
            "enterpriseBasicInfo":{
                "enterpriseIdCardType":"2",
                "enterpriseIdCardNo":"911303027692227622",
                "enterpriseName":"一天开花有限公司",
                "enterpriseRegistDate":"20210423",
                "enterpriseRegistCurrency":"CNY",
                "enterpriseRegistCapital":"54325500",
                "enterpriseArea":"110101",
                "enterpriseDetailAddr":"北京市海淀区北清路81号",
                "enterprisePhone":"0564-2560740",
                "enterpriseMobile":"17664222137",
                "enterpriseNationality":"CHN",
                "enterpriseClassification":"99",
                "enterpriseCategory":"201",
                "enterpriseStopSign":"01",
                "labourIntensiveSign":"Y",
                "ruralCitySign":"N",
                "domesticOverseasSign":"I",
                "groupCustomersSign":"N",
                "parentCompany":"",
                "shareholdingRatio":"",
                "industry":"A0111",
                "businessScope":"医疗",
                "paidInCapitalCurrency":"CNY",
                "paidInCapital":"44",
                "employeeNumber":"34",
                "sellSum":"444",
                "totalAssets":"555",
                "listedCompanySign":"N",
                "listedPlace":"",
                "listedCompanyStockCode":"",
                "listedCountry":"",
                "businessStatus":"06",
                "economicComponents":"A0201",
                "nationalEconomicSector":"A05",
                "baseAccount":"305296870918377623",
                "baseAccountBankName":"中国邮政",
                "cardStartDate":"20151201",
                "cardEndDate":"20991231"
            },
            "corporationBasicInfo":{
                "corporationName":"张翰",
                "corporationIdCardType":"1",
                "corporationIdCardNo":"130302197902277622",
                "corporationIdStartDate":"20150401",
                "corporationIdEndDate":"20250401",
                "corporationSex":"M",
                "corporationNationality":"CHN",
                "corporatioJob":"0",
                "corporationMobile":"17664222137"
            },
            "authLoanExtInfo":{
                "serviceAddress":"北京",
                "postalCode":"121231",
                "corporationName":"张翰",
                "contactsName":"冬冬6",
                "contactTelephone":"17664222137",
                "totalAccountsReceivableAmount":"",
                "loanAmt":"",
                "loanEndDate":"",
                "accountsReceivableList":""
            },
            "controllerList":[
                {
                    "controllerName":"冬冬5",
                    "controllerIdCardType":"1",
                    "controllerIdCardNo":"342401199609097631",
                    "controllerIdStartDate":"20150401",
                    "controllerIdEndDate":"20250401",
                    "controllerMobile":"17664222137"
                }
            ],
            "shareholderList":[
                {
                    "shareholderName":"冬冬3",
                    "shareholderIdCardType":"1",
                    "shareholderIdCardNo":"342401199609097631",
                    "shareholderIdStartDate":"20150401",
                    "shareholderIdEndDate":"20250401",
                    "shareholderInvestmentRatio":"22"
                }
            ],
            "beneficiaryOwnersList":[
                {
                    "beneficiaryOwnersName":"冬冬2",
                    "beneficiaryOwnersIdCardType":"1",
                    "beneficiaryOwnersIdCardNo":"342401199609097631",
                    "beneficiaryOwnersIdStartDate":"20150401",
                    "beneficiaryOwnersIdEndDate":"20250401",
                    "beneficiaryOwnersMobile":"17664222137",
                    "beneficiaryOwnersAddr":"北京"
                }
            ],
            "authorizedAgentBasicInfo":{
                "authorizedAgentName":"冬冬1",
                "authorizedAgentIdCardType":"1",
                "authorizedAgentIdCardNo":"342401199609097631",
                "authorizedAgentIdStartDate":"20150401",
                "authorizedAgentIdEndDate":"20250401",
                "authorizedAgentMobile":"17664222137"
            },
            "contactList":[
                {
                    "contactRelation":"2",
                    "contactName":"冬冬4",
                    "contactMobile":"17664222137"
                }
            ],
            "fileList":[
                {
                    "uid":"1619169367734",
                    "fileId":"60829116c0a4710007ce6b4f",
                    "fileName":"1.jpg",
                    "contentType":"",
                    "size":58231,
                    "updateTime":"",
                    "md5":"",
                    "content":"",
                    "hash":"",
                    "dataPoolURL":"",
                    "description":"",
                    "type":"0105",
                    "name":"1.jpg",
                    "status":"success",
                    "fileAddr":"/api/files/file/query/60829116c0a4710007ce6b4f"
                },
                {
                    "uid":"1619169371003",
                    "fileId":"60829119c0a4710007ce6b51",
                    "fileName":"2.jpg",
                    "contentType":"",
                    "size":40290,
                    "updateTime":"",
                    "md5":"",
                    "content":"",
                    "hash":"",
                    "dataPoolURL":"",
                    "description":"",
                    "type":"0106",
                    "name":"2.jpg",
                    "status":"success",
                    "fileAddr":"/api/files/file/query/60829119c0a4710007ce6b51"
                },
                {
                    "uid":"1619169374558",
                    "fileId":"6082911dc0a4710007ce6b53",
                    "fileName":"3.jpg",
                    "contentType":"",
                    "size":53157,
                    "updateTime":"",
                    "md5":"",
                    "content":"",
                    "hash":"",
                    "dataPoolURL":"",
                    "description":"",
                    "type":"0101",
                    "name":"3.jpg",
                    "status":"success",
                    "fileAddr":"/api/files/file/query/6082911dc0a4710007ce6b53"
                },
                {
                    "uid":"1619169378151",
                    "fileId":"60829120c0a4710007ce6b55",
                    "fileName":"4.jpg",
                    "contentType":"",
                    "size":58317,
                    "updateTime":"",
                    "md5":"",
                    "content":"",
                    "hash":"",
                    "dataPoolURL":"",
                    "description":"",
                    "type":"0118",
                    "name":"4.jpg",
                    "status":"success",
                    "fileAddr":"/api/files/file/query/60829120c0a4710007ce6b55"
                },
                {
                    "uid":1620280221606,
                    "size":252030,
                    "fileId":"60938450c0a4710007ce6d5b",
                    "fileName":"发票3.jpg",
                    "name":"发票3.jpg",
                    "status":"success",
                    "type":"0123",
                    "fileAddr":"/api/files/file/query/60938450c0a4710007ce6d5b"
                },
                {
                    "uid":"1619169383138",
                    "fileId":"60829125c0a4710007ce6b57",
                    "fileName":"5.jpg",
                    "contentType":"",
                    "size":55985,
                    "updateTime":"",
                    "md5":"",
                    "content":"",
                    "hash":"",
                    "dataPoolURL":"",
                    "description":"",
                    "type":"0114",
                    "name":"5.jpg",
                    "status":"success",
                    "fileAddr":"/api/files/file/query/60829125c0a4710007ce6b57"
                },
                {
                    "uid":"1619169387254",
                    "fileId":"60829129c0a4710007ce6b59",
                    "fileName":"6.jpg",
                    "contentType":"",
                    "size":53090,
                    "updateTime":"",
                    "md5":"",
                    "content":"",
                    "hash":"",
                    "dataPoolURL":"",
                    "description":"",
                    "type":"0115",
                    "name":"6.jpg",
                    "status":"success",
                    "fileAddr":"/api/files/file/query/60829129c0a4710007ce6b59"
                },
                {
                    "uid":"1619169390776",
                    "fileId":"6082912dc0a4710007ce6b5b",
                    "fileName":"7.jpg",
                    "contentType":"",
                    "size":63302,
                    "updateTime":"",
                    "md5":"",
                    "content":"",
                    "hash":"",
                    "dataPoolURL":"",
                    "description":"",
                    "type":"0116",
                    "name":"7.jpg",
                    "status":"success",
                    "fileAddr":"/api/files/file/query/6082912dc0a4710007ce6b5b"
                },
                {
                    "uid":1620280226293,
                    "size":549598,
                    "fileId":"60938457c0a4710007ce6d5d",
                    "fileName":"发票2.jpg",
                    "name":"发票2.jpg",
                    "status":"success",
                    "type":"0117",
                    "fileAddr":"/api/files/file/query/60938457c0a4710007ce6d5d"
                },
                {
                    "uid":1620280237233,
                    "size":158007,
                    "fileId":"6093845fc0a4710007ce6d61",
                    "fileName":"发票.jpg",
                    "name":"发票.jpg",
                    "status":"success",
                    "type":"0112",
                    "fileAddr":"/api/files/file/query/6093845fc0a4710007ce6d61"
                },
                {
                    "uid":1620280242124,
                    "size":38868,
                    "fileId":"60938463c0a4710007ce6d63",
                    "fileName":"滴滴电子发票.pdf",
                    "name":"滴滴电子发票.pdf",
                    "status":"success",
                    "type":"0113",
                    "fileAddr":"/api/files/file/query/60938463c0a4710007ce6d63"
                },
                {
                    "uid":"1619169394551",
                    "fileId":"60829131c0a4710007ce6b5d",
                    "fileName":"8.jpg",
                    "contentType":"",
                    "size":97420,
                    "updateTime":"",
                    "md5":"",
                    "content":"",
                    "hash":"",
                    "dataPoolURL":"",
                    "description":"",
                    "type":"0102",
                    "name":"8.jpg",
                    "status":"success",
                    "fileAddr":"/api/files/file/query/60829131c0a4710007ce6b5d"
                },
                {
                    "uid":"1619169398740",
                    "fileId":"60829135c0a4710007ce6b5f",
                    "fileName":"9.jpg",
                    "contentType":"",
                    "size":61747,
                    "updateTime":"",
                    "md5":"",
                    "content":"",
                    "hash":"",
                    "dataPoolURL":"",
                    "description":"",
                    "type":"0103",
                    "name":"9.jpg",
                    "status":"success",
                    "fileAddr":"/api/files/file/query/60829135c0a4710007ce6b5f"
                }
            ],
            "needSMSVerification":"0",
            "custMobile":"17664222137",
            "idCardNo":"911303027692227622",
            "cardStartDate":"20151201",
            "cardEndDate":"20991231"
        },
        "creditExtInfo":{
            "loanTopCustomerList":[
                {
                    "companyName":"冬冬8",
                    "salesAmount":"465",
                    "salesAmountRatio":"44"
                }
            ],
            "growthRate":"11",
            "workingCapitalLoan":"346534654635",
            "otherWorkingCapital":"2362634526",
            "logisticsName":"北京精密电子有限公司",
            "logisticsIdCardType":"0",
            "logisticsIdCardNo":"911303027692273987",
            "logisticsIdStartDate":"20151201",
            "logisticsIdEndDate":"20991231",
            "logisticsRegisteredAddress":"北京市海淀区",
            "logisticsActualAddress":"北京市海淀区北清路81号",
            "logisticsIndustry":"A0111",
            "logisticsRegisteredCapital":"54325500",
            "logisticsPaidInCapital":"50000000",
            "logisticsComponents":"205",
            "logisticsBusinessScope":"金融信息服务，计算机网络专业领域内的技术开发、技术咨询、技术服务、技术转让，计算机系统集成及软硬件的开发与销售，数据处理服务，电子商务（不得从事金融业务），电信业务，市场信息咨询与调查（不得从事社会调查、社会调研、民意调查、民意测验），会展服务，企业管理咨询、投资咨询，企业形象策划，广告的设计、制作。【依法须经批准的项目，经相关部门批准后方可开展经营活动】",
            "logisticsCorporationName":"孟美丽",
            "logisticsCorporationNationality":"CHN",
            "logisticsCorporationSex":"M",
            "logisticsCorporationIdCardType":"IT01",
            "logisticsCorporationIdCardNo":"130302197902271987",
            "logisticsCorporationIdStartDate":"20200430",
            "logisticsCorporationIdEndDate":"20250430",
            "logisticsAffiliatedCompany":"Y",
            "logisticsLastYearNetProfit":"1500",
            "logisticsOwnedCarNo":"300",
            "logisticsRecordedCarNo":"100",
            "logisticsTopCustomerList":[
                {
                    "companyName":"冬冬",
                    "salesAmount":"150",
                    "salesAmountRatio":"35"
                },
                {
                    "companyName":"张张",
                    "salesAmount":"300",
                    "salesAmountRatio":"70"
                }
            ],
            "logisticsCorporationBadHabits":"N",
            "constructionName":"上海滩有限公司",
            "constructionIdCardType":"0",
            "constructionIdCardNo":"911303027692273634",
            "constructionIdStartDate":"20151201",
            "constructionIdEndDate":"20991231",
            "constructionRegisteredAddress":"上海",
            "constructionActualAddress":"北京市海淀区北清路81号",
            "constructionIndustry":"C1433",
            "constructionRegisteredCapital":"54325500",
            "constructionComponents":"202",
            "constructionBusinessScope":"金融信息服务，计算机网络专业领域内的技术开发、技术咨询、技术服务、技术转让，计算机系统集成及软硬件的开发与销售，数据处理服务，电子商务（不得从事金融业务），电信业务，市场信息咨询与调查（不得从事社会调查、社会调研、民意调查、民意测验），会展服务，企业管理咨询、投资咨询，企业形象策划，广告的设计、制作。【依法须经批准的项目，经相关部门批准后方可开展经营活动】",
            "constructionCorporationName":"上海滩",
            "constructionStateOwned":"N",
            "constructionStateOwnedSubsidiary":"N",
            "constructionStateOwnedSubSubsidiary":"N",
            "constructionCentralEnterprise":"N",
            "constructionCentralSubsidiary":"N",
            "constructionCentralSubSubsidiary":"N",
            "constructionListed":"N",
            "constructionSubListed":"N",
            "constructionSubSubListed":"N",
            "nationalKeyProject":"N",
            "provinceKeyProject":"N",
            "districtKeyProject":"N",
            "fundsSource":"应收账款",
            "averageConstructionPeriod":"15",
            "longestConstructionPeriod":"30"
        }
    }
}

#字段校验参数
error_data_no_parameter = [
    {"check":"请选择企业地区码"}
]
#校验企业注册日期
error_data_code_for_enterpriseRegistDate = [
    {'enterpriseRegistDate':'2021-05-06','check':'请选择企业地区码'},
    {'enterpriseRegistDate':' ','check':'请输入企业注册日期'}
]
#校验企业地区码

#校验企业移动电话

#客户分类

#校验客户细类

